version: "3"
services:
      blackjack-client:
        image:  blackjack-client-prod
        restart: unless-stopped
        stdin_open: true

      blackjack-server:
        image: blackjack-server-prod
        restart: unless-stopped

