version: "3"
services:
      blackjack-client:
        image:  blackjack-client
        stdin_open: true
        build: ./client/
        ports:
          - "3000:3000"
        networks:
          - blackjack-network
        volumes: 
          - ./client/:/usr/app

      blackjack-server:
        image: blackjack-server
        build: ./server/
        ports:
          - "5000:5000"
        networks:
          - blackjack-network
        volumes: 
          - ./server/:/usr/app
        depends_on: 
          - mongo
      mongo:
        image: mongo
        networks: 
          - blackjack-network
        ports:
          - "27017:27017"
        volumes: 
          - blackjack-mongo-volumes:/data/db

networks:
  blackjack-network:
    driver: bridge
volumes:
  blackjack-mongo-volumes:
    driver: local

